version: '3.7'

# Environment mongo

services:

  mongo:
    image: mongo:4.2.3
    container_name: mongo_4.2.3
    ports:
      - 27017:27017
    volumes:
      - ./databases_volumes/mongodb/data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root

  mongo_express:
    image: mongo-express:latest
    container_name: mongo_express_gui_latest
    ports:
      - 5002:8081
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=root
    depends_on:
      - mongo
